name: William Woodall
markdown: redcarpet
highlighter: pygments

url: http://wjwwood.io

author:
  name: William Woodall
  email: wjwwood@gmail.com
  github: wjwwood
  twitter: wjwwood
  feedname: github/OZFQ
